### ISSUE TITLE
Feature request: context instead of timeouts

### ISSUE THREAD

**Issue by zerkms** [essentialkaos/sslscan#75]
_Before opening an issue, search for similar bug reports or feature requests on GitHub Issues. If yes, please add a_ 👍 _reaction to the existing issue. If no similar issue can be found, fill out either the "Bug Report" or the "Feature Request" section below. Erase the other section and everything on and above this line._

### Feature Request

Opening a feature request kicks off a discussion. Requests may be closed if we're not actively planning to work on them.

**Proposal:**

`fasthttp.Client` implements `DoDeadline` (https://github.com/valyala/fasthttp/blob/56775f4d9fa114edf7f860abfe95294b58e61020/client.go#L2241)

How about changing api of `Analyze`, `Info`, and `GetEndpointInfo` so that all of them accepted `context.Context`, and then `context.Context.Deadline()` is used to obtain the client operation deadline.

**Current behavior:**

It's hardcoded to 10 seconds at https://github.com/essentialkaos/sslscan/blob/c78b03e3977b5915d061989cc811739c66dca04b/sslscan.go#L510

**Desired behavior:**

I think it would be more in line with general clients expectations: when a caller provides timeout/deadline expectations

**Use case:**

In case if the caller side does not want results anymore - no need to retain resources (memory and sockets) for more than necessary, and make the caller wait for up to extra 10 seconds.

I'm ready to implement it we agree on the implementation details and project owner vision.

**Comment by andyone** [comment]
Hi! Thanks for detailed feature request.

> It's hardcoded to 10 seconds at

It's a public variable with default timeouts and can be changed from your code as well. Also, you can configure `API.Client` after creating a new API struct. So there is a lot of customization options.

> In case if the caller side does not want results anymore - no need to retain resources (memory and sockets) for more than necessary, and make the caller wait for up to extra 10 seconds.

`DoDeadline` does not accept context, only `time.Time` with Deadline date and time. So you can't cancel your request. Could you please clarify your idea behind using context?

**Comment by zerkms** [comment]
Oh, I'm not sure how it happened that I misread `time.Time` with `context.Context` :facepalm:

**Comment by andyone** [comment]
I have a little bit changed working with request timeout in the new version. In the last version, `RequestTimeout` type changed to `time.Duration`, and we use this value with `DoTimeout` method. Also, it makes it easier to change the timeout for `API` instance through `RequestTimeout` property.
