### ISSUE TITLE
Feature request: typed error for non-http-200 responses

### ISSUE THREAD

**Issue by zerkms** [essentialkaos/sslscan#76]
_Before opening an issue, search for similar bug reports or feature requests on GitHub Issues. If yes, please add a_ 👍 _reaction to the existing issue. If no similar issue can be found, fill out either the "Bug Report" or the "Feature Request" section below. Erase the other section and everything on and above this line._

### Feature Request

Opening a feature request kicks off a discussion. Requests may be closed if we're not actively planning to work on them.

**Proposal:**

Typed errors for different response types for ease of handling it

**Current behavior:**

At the moment non-http-200 responses trigger a generic string error

https://github.com/essentialkaos/sslscan/blob/c78b03e3977b5915d061989cc811739c66dca04b/sslscan.go#L641-L645

Which means if a caller wants to handle different responses differently - eg: wait significantly longer for 529 they need to parse text error.

What if a dedicated type `HttpError` was introduced, which held status code (and may be even the response body).

**Desired behavior:**

Have easier way to assert if it was http error, or something else.

**Use case:**

Depending on http status codes the caller actions might be different. At the moment it's required to parse error string to extract the status code value.

I'm ready to implement it we agree on the implementation details and project owner vision.

**Comment by andyone** [comment]
Hi! Thanks for detailed feature request.

Great idea! I'll add this in the next version.

**Comment by andyone** [comment]
This feature was implemented as part of #77
